mean: [-0.4998334646, 1.0110057592, 0.5704032183, 0.3171823621]
std:  [0.4102624059, 0.3251966834, 0.2688823938, 1.1192697287] # whole dataset 

# mean: [-0.6123741269111633, 1.1049565076828003, 0.5699091553688049, 0.7600371837615967] 
# std: [0.32270529866218567, 0.26031994819641113, 0.18459899723529816, 0.9349327087402344] # temp dataset 